2004-03-09  Michael Koch  <konqueror@gmx.de>
	* java/lang/Thread.java
	(runnable): Moved around.
	(daemon): Renamed from daemon_flag.
	(contextClassLoader): Renamed from context_class_loader.
	(Thread): Reordered constructors.
	(activeCount): Use group directly.
	(destroy): Make it a java method. Throw NoSuchMethodError like Sun does.
	(holdsLock): Reworked javadoc.
	(setDaemon): Reworked.
	* java/lang/natThread.cc
	(destroy): Removed.


git-svn-id: svn://gcc.gnu.org/svn/gcc/trunk@79200 138bc75d-0d04-0410-961f-82ee72b054a4