* java/lang/natClass.cc (initializeClass): Throw NoClassDefFoundError 	with getName() as message. 	(_Jv_CheckArrayStore): Throw ArrayStoreException with object and array 	type as message.
	* java/lang/natVMThrowable.cc: Don't declare parameter t, it is
	unused.


git-svn-id: svn://gcc.gnu.org/svn/gcc/trunk@58991 138bc75d-0d04-0410-961f-82ee72b054a4